CREATE TABLE `db_location_uploads`.`survey_dev` (
  `carnet` VARCHAR(25) NOT NULL,
  `id_entrevistado` VARCHAR(18) NOT NULL,
  `edad` INT UNSIGNED NULL,
  `estado_civil` VARCHAR(30) NULL,
  `sexo` VARCHAR(10) NULL,
  `twitter` VARCHAR(45) NULL,
  `hijos` INT UNSIGNED NULL,
  `vive` VARCHAR(20) NULL,
  `ocupacion` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `barrio` VARCHAR(45) NULL,
  `vivienda` VARCHAR(30) NULL,
  `gastos_transporte` INT UNSIGNED NULL,
  `gastos_alimentacion` INT UNSIGNED NULL,
  `gastos_seguridad_social` INT UNSIGNED NULL,
  `gastos_porcentaje_ahorro` INT UNSIGNED NULL,
  `gastos_total` INT UNSIGNED NULL,
  `cultura_ciudadana` INT UNSIGNED NULL,
  `medio_ambiente` INT UNSIGNED NULL,
  `movilidad` INT UNSIGNED NULL,
  `calidad_vida` INT UNSIGNED NULL,
  `practicas_democraticas` INT UNSIGNED NULL,
  `ataques_cardiacos` INT UNSIGNED NULL,
  `hipertension` INT UNSIGNED NULL,
  `derrames_cerebrales` INT UNSIGNED NULL,
  `gastritis_cronica` INT UNSIGNED NULL,
  `cancer` INT UNSIGNED NULL,
  `gripas_refriados` INT UNSIGNED NULL,
  `gastritis` INT UNSIGNED NULL,
  `jaquecas` INT UNSIGNED NULL,
  `insomnio` INT UNSIGNED NULL,
  `ansiedad` INT UNSIGNED NULL,
  `visitas_doctor` INT UNSIGNED NULL,
  `gastos_medicamentos` INT UNSIGNED NULL,
  `dias_incapacitado` INT UNSIGNED NULL,
  `ruido_exterior_suenho` VARCHAR(20) NULL,
  `suenho_rutina` VARCHAR(20) NULL,
  `pagar_uber_taxi` VARCHAR(20) NULL,
  `ruido_barrio` INT UNSIGNED NULL,
  `ruido_transporte_publico` INT UNSIGNED NULL,
  `ruido_bogota` INT UNSIGNED NULL,
  `ejercicio_semana` INT UNSIGNED NULL,
  `parques` VARCHAR(20) NULL,
  `hora_levantar` INT UNSIGNED NULL,
  `hora_salir_hogar` INT UNSIGNED NULL,
  `hora_llegar_destino` INT UNSIGNED NULL,
  `hora_volver_hogar` INT UNSIGNED NULL,
  `dias_caminata` INT UNSIGNED NULL,
  `dias_bicicleta` INT UNSIGNED NULL,
  `dias_transmilenio` INT UNSIGNED NULL,
  `dias_uber` INT UNSIGNED NULL,
  `dias_taxi` INT UNSIGNED NULL,
  `dias_bus` INT UNSIGNED NULL,
  `dias_sitp` INT UNSIGNED NULL,
  `dias_carro` INT UNSIGNED NULL,
  `numero_atracos` INT UNSIGNED NULL,
  `dinero_atracos` INT UNSIGNED NULL,
  `mi_calidad_aire` INT UNSIGNED NULL,
  `politicos_calidad_aire` INT UNSIGNED NULL,
  `mockus_calidad_aire` INT UNSIGNED NULL,
  `lucho_calidad_aire` INT UNSIGNED NULL,
  `samuel_calidad_aire` INT UNSIGNED NULL,
  `petro_calidad_aire` INT UNSIGNED NULL,
  `penhalosa_calidad_aire` INT UNSIGNED NULL,
  `mi_seguridad_hurtos` INT UNSIGNED NULL,
  `politicos_seguridad_hurtos` INT UNSIGNED NULL,
  `mockus_seguridad_hurtos` INT UNSIGNED NULL,
  `lucho_seguridad_hurtos` INT UNSIGNED NULL,
  `samuel_seguridad_hurtos` INT UNSIGNED NULL,
  `petro_seguridad_hurtos` INT UNSIGNED NULL,
  `penhalosa_seguridad_hurtos` INT UNSIGNED NULL,
  `mi_parques_zonas_verdes` INT UNSIGNED NULL,
  `politicos_parques_zonas_verdes` INT UNSIGNED NULL,
  `mockus_parques_zonas_verdes` INT UNSIGNED NULL,
  `lucho_parques_zonas_verdes` INT UNSIGNED NULL,
  `samuel_parques_zonas_verdes` INT UNSIGNED NULL,
  `petro_parques_zonas_verdes` INT UNSIGNED NULL,
  `penhalosa_parques_zonas_verdes` INT UNSIGNED NULL,
  `mi_seguridad_peaton` INT UNSIGNED NULL,
  `politicos_seguridad_peaton` INT UNSIGNED NULL,
  `mockus_seguridad_peaton` INT UNSIGNED NULL,
  `lucho_seguridad_peaton` INT UNSIGNED NULL,
  `samuel_seguridad_peaton` INT UNSIGNED NULL,
  `petro_seguridad_peaton` INT UNSIGNED NULL,
  `penhalosa_seguridad_peaton` INT UNSIGNED NULL,
  `mi_plantar_arboles` INT UNSIGNED NULL,
  `politicos_plantar_arboles` INT UNSIGNED NULL,
  `mockus_plantar_arboles` INT UNSIGNED NULL,
  `lucho_plantar_arboles` INT UNSIGNED NULL,
  `samuel_plantar_arboles` INT UNSIGNED NULL,
  `petro_plantar_arboles` INT UNSIGNED NULL,
  `penhalosa_plantar_arboles` INT UNSIGNED NULL,
  `mi_control_ruido` INT UNSIGNED NULL,
  `politicos_control_ruido` INT UNSIGNED NULL,
  `mockus_control_ruido` INT UNSIGNED NULL,
  `lucho_control_ruido` INT UNSIGNED NULL,
  `samuel_control_ruido` INT UNSIGNED NULL,
  `petro_control_ruido` INT UNSIGNED NULL,
  `penhalosa_control_ruido` INT UNSIGNED NULL,
  `mi_mejoramiento_transporte` INT UNSIGNED NULL,
  `politicos_mejoramiento_transporte` INT UNSIGNED NULL,
  `mockus_mejoramiento_transporte` INT UNSIGNED NULL,
  `lucho_mejoramiento_transporte` INT UNSIGNED NULL,
  `samuel_mejoramiento_transporte` INT UNSIGNED NULL,
  `petro_mejoramiento_transporte` INT UNSIGNED NULL,
  `penhalosa_mejoramiento_transporte` INT UNSIGNED NULL,
  `mi_cultura_ciudadana` INT UNSIGNED NULL,
  `politicos_cultura_ciudadana` INT UNSIGNED NULL,
  `mockus_cultura_ciudadana` INT UNSIGNED NULL,
  `lucho_cultura_ciudadana` INT UNSIGNED NULL,
  `samuel_cultura_ciudadana` INT UNSIGNED NULL,
  `petro_cultura_ciudadana` INT UNSIGNED NULL,
  `penhalosa_cultura_ciudadana` INT UNSIGNED NULL,
  `tarot_calidad` VARCHAR(2000) NULL,
  `tarot_ambiental` VARCHAR(2000) NULL,
  `tarot_cultura` VARCHAR(2000) NULL,
  `tarot_democraticas` VARCHAR(2000) NULL,
  `tarot_movilidad` VARCHAR(2000) NULL);
